# Generated by Django 2.2 on 2019-11-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stcaclient',
            name='time_seed',
            field=models.CharField(max_length=1024),
        ),
    ]
