# Generated by Django 2.2 on 2019-11-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stca', '0002_auto_20191130_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='stcatimedauthenticationperm',
            name='is_permitted',
            field=models.BooleanField(default=False),
        ),
    ]
